#
# Copyright Altoros. All Rights Reserved.
#

version: '2'

services:

  ca.c.example.com:
    container_name: ca.c.example.com
    image: hyperledger/fabric-ca:x86_64-1.1.0-preview
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.c.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/add3d5d31930836b593aeec1d2efadb921ceefd5ee6ed97cdfa63a3cbe0238cf_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.c.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/add3d5d31930836b593aeec1d2efadb921ceefd5ee6ed97cdfa63a3cbe0238cf_sk
#    ports:
#      - 9054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/c.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../artifacts/fabric-ca-server-config-c.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml

  peer0.c.example.com:
    container_name: peer0.c.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.c.example.com
      - CORE_PEER_LOCALMSPID=cMSP
      - CORE_PEER_ADDRESS=peer0.c.example.com:7051
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/c.example.com/peers/peer0.c.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - ca.c.example.com
    

  peer1.c.example.com:
    container_name: peer1.c.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.c.example.com
      - CORE_PEER_LOCALMSPID=cMSP
      - CORE_PEER_ADDRESS=peer1.c.example.com:7051
    ports:
      - 9056:7051
      - 9058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/c.example.com/peers/peer1.c.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - ca.c.example.com
    

  # fabric-rest api server
  api.c.example.com:
    extends:
      file: base.yaml
      service: api-base
    container_name: api.c.example.com
    ports:
      - 4002:4000
    environment:
      - ORG=c
      - PORT=4000
    depends_on:
      - peer0.c.example.com
      - peer1.c.example.com
    

  cli.example.com:
    container_name: cli.example.com
    extends:
      file: base.yaml
      service: cli-base
    volumes:
      - ../artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/etc/hyperledger/crypto/orderer/tls

  cli.c.example.com:
    container_name: cli.c.example.com
    extends:
      service: cli.example.com
    environment:
      - CORE_PEER_LOCALMSPID=cMSP
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/c.example.com/users/Admin@c.example.com:/etc/hyperledger/crypto/peer
    

  # simple http server to disseminate certificates
  www.c.example.com:
    extends:
      file: base.yaml
      service: www-base
    container_name: www.c.example.com
    ports:
      - 8083:80
